/**
 * Setup links: `obsidian://notekit-edit?v=1&type=…` URLs that describe one agent, so a phone can be
 * set up by scanning a QR code with its camera. The format is documented in docs/setup-links.md and
 * is meant to be generated by other software too, so keep it stable and backwards compatible.
 *
 * No `obsidian` imports: the bridge uses buildSetupLink() to print its QR code.
 *
 * Security: a link can only describe network agents (`openai`, `anthropic`). It can never create a
 * local agent (claude-code, codex-cli, acp) or set a command, because opening a link must not be
 * able to make the plugin start a program. The plugin also asks for confirmation before saving.
 */
import type { Effort } from "./settings";

export const SETUP_LINK_ACTION = "notekit-edit";
export const SETUP_LINK_VERSION = "1";

export type SetupLinkType = "openai" | "anthropic";

/** The agent fields a setup link may carry, already validated. */
export interface SetupLinkAgent {
  type: SetupLinkType;
  name: string;
  baseUrl: string;
  apiKey: string;
  model: string;
  effort?: Effort;
  headers: string;
}

export type SetupLinkResult = { ok: true; agent: SetupLinkAgent; makeDefault: boolean } | { ok: false; error: string };

export interface SetupLinkInput {
  type: SetupLinkType;
  url?: string;
  key?: string;
  model?: string;
  name?: string;
  effort?: Effort;
  /** `Name: value` lines separated by newlines. */
  headers?: string;
  makeDefault?: boolean;
  /** Obsidian's own parameter: the vault to open. */
  vault?: string;
}

const EFFORTS: Effort[] = ["low", "medium", "high", "xhigh", "max"];
const MAX_VALUE = 4096;
const MAX_NAME = 80;
export const DEFAULT_ANTHROPIC_MODEL = "claude-opus-5";

/** Builds a setup link. Every value is percent-encoded, so the result is plain ASCII. */
export function buildSetupLink(cfg: SetupLinkInput): string {
  const params: Array<[string, string | undefined]> = [
    ["v", SETUP_LINK_VERSION],
    ["type", cfg.type],
    ["name", cfg.name],
    ["url", cfg.url],
    ["model", cfg.model],
    ["key", cfg.key],
    ["effort", cfg.effort],
    ["headers", cfg.headers],
    ["default", cfg.makeDefault === undefined ? undefined : String(cfg.makeDefault)],
    ["vault", cfg.vault],
  ];
  const query = params
    .filter((p): p is [string, string] => typeof p[1] === "string" && p[1] !== "")
    .map(([k, v]) => `${k}=${encodeURIComponent(v)}`)
    .join("&");
  return `obsidian://${SETUP_LINK_ACTION}?${query}`;
}

/**
 * Validates decoded setup-link parameters (what Obsidian hands a protocol handler, or the query of
 * a pasted link). Unknown parameters are ignored so newer generators stay readable.
 */
export function parseSetupLink(params: Record<string, string | undefined>): SetupLinkResult {
  const get = (k: string) => (params[k] ?? "").trim();
  const fail = (error: string): SetupLinkResult => ({ ok: false, error });

  const v = get("v");
  if (!v) return fail("This is not a Notekit Edit setup link (the version parameter is missing).");
  if (v !== SETUP_LINK_VERSION) return fail(`This setup link uses format version ${v}. Update Notekit Edit to read it.`);

  if ("command" in params || "allowTools" in params) {
    return fail("Setup links cannot set a command. Local agents have to be added in the settings.");
  }
  const type = get("type");
  if (type === "claude-code" || type === "codex-cli" || type === "acp") {
    return fail("Setup links cannot add local agents that run a program. Add them in the settings instead.");
  }
  if (type !== "openai" && type !== "anthropic") return fail(`Unknown agent type “${type || "(none)"}”.`);

  for (const k of ["name", "url", "model", "key", "effort", "headers"]) {
    if (get(k).length > MAX_VALUE) return fail(`The “${k}” value of this setup link is too long.`);
  }

  let baseUrl = get("url").replace(/\/+$/, "");
  if (baseUrl) {
    let parsed: URL;
    try {
      parsed = new URL(baseUrl);
    } catch {
      return fail(`“${baseUrl}” is not a valid URL.`);
    }
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return fail("The base URL must start with http:// or https://.");
    if (parsed.username || parsed.password) return fail("The base URL must not contain a user name or password; use the key parameter.");
    baseUrl = parsed.toString().replace(/\/+$/, "");
  } else if (type === "openai") {
    return fail("An OpenAI-compatible setup link needs a base URL (url).");
  }

  let model = get("model");
  if (!model) {
    if (type === "openai") return fail("An OpenAI-compatible setup link needs a model name (model).");
    model = DEFAULT_ANTHROPIC_MODEL;
  }

  const effortRaw = get("effort");
  let effort: Effort | undefined;
  if (effortRaw) {
    if (type !== "anthropic") return fail("The effort parameter only applies to Anthropic agents.");
    if (!EFFORTS.includes(effortRaw as Effort)) return fail(`Unknown effort “${effortRaw}”. Use ${EFFORTS.join(", ")}.`);
    effort = effortRaw as Effort;
  }

  const headers = get("headers")
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  for (const line of headers) {
    if (line.indexOf(":") <= 0) return fail(`Header line “${line}” is not in the form “Name: value”.`);
  }

  const name = get("name").slice(0, MAX_NAME) || defaultName(type, baseUrl);
  const def = get("default").toLowerCase();
  return {
    ok: true,
    agent: { type, name, baseUrl, apiKey: get("key"), model, effort, headers: headers.join("\n") },
    makeDefault: def !== "false" && def !== "0",
  };
}

/** Parses a pasted `obsidian://notekit-edit?…` link. */
export function parseSetupLinkUrl(text: string): SetupLinkResult {
  const trimmed = text.trim();
  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    return { ok: false, error: "That is not a link. Paste the whole obsidian://notekit-edit?… link." };
  }
  const action = (url.host || url.pathname).replace(/^\/+|\/+$/g, "");
  if (url.protocol !== "obsidian:" || action !== SETUP_LINK_ACTION) {
    return { ok: false, error: "That is not a Notekit Edit setup link. It should start with obsidian://notekit-edit?" };
  }
  const params: Record<string, string> = {};
  url.searchParams.forEach((value, key) => (params[key] = value));
  return parseSetupLink(params);
}

function defaultName(type: SetupLinkType, baseUrl: string): string {
  if (type === "anthropic") return "Claude (API key)";
  try {
    return `OpenAI-compatible (${new URL(baseUrl).host})`;
  } catch {
    return "OpenAI-compatible";
  }
}

/**
 * True for plain http:// to a host outside the local network, where the key and the notes would
 * cross the internet unencrypted. Used for a warning, not to block.
 */
export function isInsecureRemoteUrl(baseUrl: string): boolean {
  let url: URL;
  try {
    url = new URL(baseUrl);
  } catch {
    return false;
  }
  if (url.protocol !== "http:") return false;
  const host = url.hostname.replace(/^\[|\]$/g, "").toLowerCase();
  if (host === "localhost" || host.endsWith(".local") || host.endsWith(".lan") || host.endsWith(".home.arpa")) return false;
  if (host === "::1" || /^f[cd][0-9a-f]{2}:/.test(host) || host.startsWith("fe80:")) return false;
  const m = host.match(/^(\d+)\.(\d+)\.\d+\.\d+$/);
  if (!m) return true;
  const a = Number(m[1]);
  const b = Number(m[2]);
  return !(a === 127 || a === 10 || (a === 192 && b === 168) || (a === 172 && b >= 16 && b <= 31) || (a === 100 && b >= 64 && b <= 127) || (a === 169 && b === 254));
}
